/**
 * Central image manifest. Canonical paths + blur placeholders for all
 * curated site imagery. Generated by `scripts/fetch-images.ts`.
 *
 * Prefer these helpers over hard-coded /images/ paths so alt-text and
 * blur placeholders come along automatically.
 */
import manifestJson from "./image-manifest.generated.json";

export type ImageCategory = "hero" | "services" | "realisations" | "realisations-before" | "zones" | "team";

export interface ImageEntry {
  slug: string;
  category: ImageCategory;
  alt: string;
  webp: string;
  jpg: string;
  width: number;
  height: number;
  blurDataURL: string;
}

const manifest = manifestJson as ImageEntry[];

const bySlug = new Map<string, ImageEntry>(manifest.map((e) => [e.slug, e]));

/** Get an image entry by slug. Throws if not found — fail loud in dev. */
export function image(slug: string): ImageEntry {
  const entry = bySlug.get(slug);
  if (!entry) {
    throw new Error(`[image-manifest] Unknown slug "${slug}". Run 'npx tsx scripts/fetch-images.ts'.`);
  }
  return entry;
}

/** Safe variant — returns null if slug missing. Use when image is optional. */
export function imageOrNull(slug: string): ImageEntry | null {
  return bySlug.get(slug) ?? null;
}

/** All images in a category, in manifest order. */
export function imagesByCategory(category: ImageCategory): ImageEntry[] {
  return manifest.filter((e) => e.category === category);
}

/** All entries (rarely needed — prefer filtering). */
export function allImages(): ImageEntry[] {
  return manifest.slice();
}

/**
 * Props spread-helper for Next/Image:
 *   <Image {...imageProps("hero-electricien")} />
 */
export function imageProps(slug: string) {
  const e = image(slug);
  return {
    src: e.webp,
    alt: e.alt,
    width: e.width,
    height: e.height,
    blurDataURL: e.blurDataURL,
    placeholder: "blur" as const,
  };
}
